{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"customer\",\"snowball_output\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.132.1053.0 (24.08)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "Entities": {
              "customer": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "customer"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "customer": {
                      "State": "Generated"
                    }
                  },
                  {
                    "customer": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "client": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "consumer": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "user": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "buyer": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "patron": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "purchaser": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "shopper": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  }
                ]
              },
              "customer.customer_country": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "customer",
                    "ConceptualProperty": "customer_country"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "customer country": {
                      "State": "Generated"
                    }
                  },
                  {
                    "customer country": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "customer_country": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "country": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "country": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.97
                    }
                  },
                  {
                    "customer nation": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "customer location": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "nation": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "location": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "client country": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "consumer country": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "user country": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "buyer country": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "patron country": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "purchaser country": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  }
                ]
              },
              "customer.customer_id": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "customer",
                    "ConceptualProperty": "customer_id"
                  }
                },
                "NameType": "Identifier",
                "State": "Generated",
                "Terms": [
                  {
                    "customer id": {
                      "State": "Generated"
                    }
                  },
                  {
                    "customer id": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "id": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "id": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.97
                    }
                  },
                  {
                    "customer_id": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "customer identification": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "customer identity": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "customer identifier": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "customer credential": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "client id": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "consumer id": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "user id": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "buyer id": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "patron id": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "purchaser id": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  }
                ]
              },
              "customer.customer_key": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "customer",
                    "ConceptualProperty": "customer_key"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "customer key": {
                      "State": "Generated"
                    }
                  },
                  {
                    "customer key": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "customer_key": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "key": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "key": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.97
                    }
                  },
                  {
                    "client key": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "consumer key": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "user key": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "buyer key": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "patron key": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "purchaser key": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "shopper key": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "main": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "basic": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "fundamental": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  }
                ]
              },
              "customer.customer_name": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "customer",
                    "ConceptualProperty": "customer_name"
                  }
                },
                "NameType": "Name",
                "State": "Generated",
                "Terms": [
                  {
                    "customer name": {
                      "State": "Generated"
                    }
                  },
                  {
                    "customer name": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "name": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "name": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.97
                    }
                  },
                  {
                    "customer_name": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "customer nickname": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "customer title": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "customer label": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "customer tag": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "customer surname": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "client name": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "consumer name": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "user name": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "buyer name": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "patron name": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  }
                ]
              },
              "customer.customer_region": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "customer",
                    "ConceptualProperty": "customer_region "
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "customer region": {
                      "State": "Generated"
                    }
                  },
                  {
                    "customer region": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "customer_region ": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "region": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "region": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.97
                    }
                  },
                  {
                    "customer_region": {
                      "State": "Generated",
                      "Weight": 0.96029999999999993
                    }
                  },
                  {
                    "customer_region": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.96029999999999993
                    }
                  },
                  {
                    "customer location": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.833
                    }
                  },
                  {
                    "location": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.818
                    }
                  },
                  {
                    "customer province": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "province": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "customer area": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "customer district": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "customer section": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "customer zone": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "customer continent": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "area": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  }
                ]
              },
              "snowball_output": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "snowball output": {
                      "State": "Generated"
                    }
                  },
                  {
                    "snowball output": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "snowball_output": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "output": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "output": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.97
                    }
                  },
                  {
                    "snowball production": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "snowball productivity": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "production": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "productivity": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "snowball yield": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "snowball harvest": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "snowball crop": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "yield": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "harvest": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "crop": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  }
                ]
              },
              "snowball_output.bop_arr": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "ConceptualProperty": "bop_arr"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "bop arr": {
                      "State": "Generated"
                    }
                  },
                  {
                    "bop arr": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "bop_arr": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  }
                ]
              },
              "snowball_output.cross_sell": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "ConceptualProperty": "cross_sell"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "cross sell": {
                      "State": "Generated"
                    }
                  },
                  {
                    "cross sell": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "cross_sell": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "sell": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "sell": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.97
                    }
                  },
                  {
                    "symbol sell": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.461
                    }
                  },
                  {
                    "mark sell": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.461
                    }
                  },
                  {
                    "sign sell": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.461
                    }
                  }
                ]
              },
              "snowball_output.customer_churn": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "ConceptualProperty": "customer_churn"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "customer churn": {
                      "State": "Generated"
                    }
                  },
                  {
                    "customer churn": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "customer_churn": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "churn": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "churn": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.97
                    }
                  },
                  {
                    "client churn": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "consumer churn": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "user churn": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "buyer churn": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "patron churn": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "purchaser churn": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "shopper churn": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  }
                ]
              },
              "snowball_output.customer_key": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "ConceptualProperty": "customer_key"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "customer key": {
                      "State": "Generated"
                    }
                  },
                  {
                    "customer key": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "customer_key": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "key": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "key": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.97
                    }
                  },
                  {
                    "client key": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "consumer key": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "user key": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "buyer key": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "patron key": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "purchaser key": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "shopper key": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "main": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "basic": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "fundamental": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  }
                ],
                "Visibility": {
                  "Value": "Hidden"
                }
              },
              "snowball_output.downsell": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "ConceptualProperty": "downsell"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "downsell": {
                      "State": "Generated"
                    }
                  },
                  {
                    "downsell": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  }
                ]
              },
              "snowball_output.eop_arr": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "ConceptualProperty": "eop_arr"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "eop arr": {
                      "State": "Generated"
                    }
                  },
                  {
                    "eop arr": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "eop_arr": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  }
                ]
              },
              "snowball_output.grr": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "ConceptualProperty": "grr"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "grr": {
                      "State": "Generated"
                    }
                  },
                  {
                    "grr": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  }
                ]
              },
              "snowball_output.month": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "ConceptualProperty": "month"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "month": {
                      "State": "Generated"
                    }
                  },
                  {
                    "month": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "mth": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  }
                ]
              },
              "snowball_output.month_roll": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "ConceptualProperty": "month_roll"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "month roll": {
                      "State": "Generated"
                    }
                  },
                  {
                    "month roll": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "month_roll": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "date": {
                      "State": "Generated",
                      "Weight": 0.7
                    }
                  },
                  {
                    "date": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.7
                    }
                  },
                  {
                    "roll": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "roll": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.97
                    }
                  },
                  {
                    "mth roll": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "month reel": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "month cylinder": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "month spool": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "month tube": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "reel": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "cylinder": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "spool": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "tube": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  }
                ]
              },
              "snowball_output.month_roll.variation.date_hierarchy": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "Hierarchy": "Date Hierarchy",
                    "VariationSet": "Variation",
                    "VariationSource": "month_roll"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "month roll date hierarchy": {
                      "State": "Generated"
                    }
                  },
                  {
                    "month roll date hierarchy": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "date hierarchy": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "date hierarchy": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.97
                    }
                  },
                  {
                    "roll date hierarchy": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "roll date hierarchy": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.97
                    }
                  }
                ]
              },
              "snowball_output.month_roll.variation.date_hierarchy.day": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "Hierarchy": "Date Hierarchy",
                    "HierarchyLevel": "Day",
                    "VariationSet": "Variation",
                    "VariationSource": "month_roll"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "month roll day": {
                      "State": "Generated"
                    }
                  },
                  {
                    "month roll day": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "day": {
                      "State": "Generated"
                    }
                  },
                  {
                    "day": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "roll day": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "roll day": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.97
                    }
                  },
                  {
                    "mth roll day": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.609
                    }
                  }
                ]
              },
              "snowball_output.month_roll.variation.date_hierarchy.month": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "Hierarchy": "Date Hierarchy",
                    "HierarchyLevel": "Month",
                    "VariationSet": "Variation",
                    "VariationSource": "month_roll"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "month roll month": {
                      "State": "Generated"
                    }
                  },
                  {
                    "month roll month": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "month": {
                      "State": "Generated"
                    }
                  },
                  {
                    "month": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "roll month": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "roll month": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.97
                    }
                  },
                  {
                    "month roll mth": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.762
                    }
                  },
                  {
                    "roll mth": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "mth": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "mth roll month": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.609
                    }
                  }
                ]
              },
              "snowball_output.month_roll.variation.date_hierarchy.quarter": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "Hierarchy": "Date Hierarchy",
                    "HierarchyLevel": "Quarter",
                    "VariationSet": "Variation",
                    "VariationSource": "month_roll"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "month roll quarter": {
                      "State": "Generated"
                    }
                  },
                  {
                    "month roll quarter": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "quarter": {
                      "State": "Generated"
                    }
                  },
                  {
                    "quarter": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "roll quarter": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "roll quarter": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.97
                    }
                  },
                  {
                    "month roll qtr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.846
                    }
                  },
                  {
                    "roll qtr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.833
                    }
                  },
                  {
                    "qtr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.818
                    }
                  },
                  {
                    "mth roll quarter": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.609
                    }
                  }
                ]
              },
              "snowball_output.month_roll.variation.date_hierarchy.year": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "Hierarchy": "Date Hierarchy",
                    "HierarchyLevel": "Year",
                    "VariationSet": "Variation",
                    "VariationSource": "month_roll"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "month roll year": {
                      "State": "Generated"
                    }
                  },
                  {
                    "month roll year": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "year": {
                      "State": "Generated"
                    }
                  },
                  {
                    "year": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "roll year": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "roll year": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.97
                    }
                  },
                  {
                    "month roll yr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.762
                    }
                  },
                  {
                    "roll yr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "yr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "mth roll year": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.609
                    }
                  }
                ]
              },
              "snowball_output.monthyear": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "ConceptualProperty": "monthyear"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "monthyear": {
                      "State": "Generated"
                    }
                  },
                  {
                    "monthyear": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  }
                ]
              },
              "snowball_output.new_customer": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "ConceptualProperty": "new_customer"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "new customer": {
                      "State": "Generated"
                    }
                  },
                  {
                    "new customer": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "new_customer": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "new client": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "new consumer": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "new user": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "new buyer": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "new patron": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "new purchaser": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "new shopper": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  }
                ]
              },
              "snowball_output.nrr": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "ConceptualProperty": "nrr"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "nrr": {
                      "State": "Generated"
                    }
                  },
                  {
                    "nrr": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  }
                ]
              },
              "snowball_output.period_type": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "ConceptualProperty": "period_type"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "period type": {
                      "State": "Generated"
                    }
                  },
                  {
                    "period type": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "period_type": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "type": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "type": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.97
                    }
                  },
                  {
                    "period category": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "period genre": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "period manner": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "period variety": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "category": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "genre": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "manner": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "variety": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "period brand": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "period class": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  }
                ]
              },
              "snowball_output.product_churn": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "ConceptualProperty": "product_churn"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "product churn": {
                      "State": "Generated"
                    }
                  },
                  {
                    "product churn": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "product_churn": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "churn": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "churn": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.97
                    }
                  },
                  {
                    "artifact churn": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "item churn": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  },
                  {
                    "merchandise churn": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  },
                  {
                    "produce churn": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  }
                ]
              },
              "snowball_output.product_key": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "ConceptualProperty": "product_key"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "product key": {
                      "State": "Generated"
                    }
                  },
                  {
                    "product key": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "product_key": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "key": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "key": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.97
                    }
                  },
                  {
                    "artifact key": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "item key": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  },
                  {
                    "merchandise key": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  },
                  {
                    "produce key": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  },
                  {
                    "main": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "basic": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "fundamental": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "central": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "major": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "keynote": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  }
                ]
              },
              "snowball_output.snowball_key": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "ConceptualProperty": "snowball_key"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "snowball key": {
                      "State": "Generated"
                    }
                  },
                  {
                    "snowball key": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "snowball_key": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "key": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "key": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.97
                    }
                  },
                  {
                    "main": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "basic": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "fundamental": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "central": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "major": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "keynote": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "essential": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "snowball solution": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.475
                    }
                  },
                  {
                    "snowball explanation": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.475
                    }
                  },
                  {
                    "snowball basis": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.475
                    }
                  }
                ]
              },
              "snowball_output.upsell": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "ConceptualProperty": "upsell"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "upsell": {
                      "State": "Generated"
                    }
                  },
                  {
                    "upsell": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  }
                ]
              },
              "snowball_output.year": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "ConceptualProperty": "Year"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "year": {
                      "State": "Generated"
                    }
                  },
                  {
                    "year": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "yr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  }
                ]
              }
            },
            "Language": "en-US",
            "Relationships": {
              "customer_has_customer_country": {
                "Binding": {
                  "ConceptualEntity": "customer"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "customer.customer_country"
                      },
                      "Subject": {
                        "Role": "customer"
                      }
                    },
                    "ID": "customers_have_customer_countries",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "customer": {
                    "Target": {
                      "Entity": "customer"
                    }
                  },
                  "customer.customer_country": {
                    "Target": {
                      "Entity": "customer.customer_country"
                    }
                  }
                },
                "State": "Generated"
              },
              "customer_has_customer_id": {
                "Binding": {
                  "ConceptualEntity": "customer"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "customer.customer_id"
                      },
                      "Subject": {
                        "Role": "customer"
                      }
                    },
                    "ID": "customers_have_customer_ids",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "ID": "customer_ids_are_names_IDs_of_customers",
                    "Name": {
                      "Name": {
                        "Role": "customer.customer_id"
                      },
                      "Subject": {
                        "Role": "customer"
                      }
                    },
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "customer": {
                    "Target": {
                      "Entity": "customer"
                    }
                  },
                  "customer.customer_id": {
                    "Target": {
                      "Entity": "customer.customer_id"
                    }
                  }
                },
                "State": "Generated"
              },
              "customer_has_customer_key": {
                "Binding": {
                  "ConceptualEntity": "customer"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "customer.customer_key"
                      },
                      "Subject": {
                        "Role": "customer"
                      }
                    },
                    "ID": "customers_have_customer_keys",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "customer": {
                    "Target": {
                      "Entity": "customer"
                    }
                  },
                  "customer.customer_key": {
                    "Target": {
                      "Entity": "customer.customer_key"
                    }
                  }
                },
                "State": "Generated"
              },
              "customer_has_customer_name": {
                "Binding": {
                  "ConceptualEntity": "customer"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "customer.customer_name"
                      },
                      "Subject": {
                        "Role": "customer"
                      }
                    },
                    "ID": "customers_have_customer_names",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "ID": "customer_names_are_names_IDs_of_customers",
                    "Name": {
                      "Name": {
                        "Role": "customer.customer_name"
                      },
                      "Subject": {
                        "Role": "customer"
                      }
                    },
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "customer": {
                    "Target": {
                      "Entity": "customer"
                    }
                  },
                  "customer.customer_name": {
                    "Target": {
                      "Entity": "customer.customer_name"
                    }
                  }
                },
                "State": "Generated"
              },
              "customer_has_customer_region": {
                "Binding": {
                  "ConceptualEntity": "customer"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "customer.customer_region"
                      },
                      "Subject": {
                        "Role": "customer"
                      }
                    },
                    "ID": "customers_have_customer_regions",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "customer": {
                    "Target": {
                      "Entity": "customer"
                    }
                  },
                  "customer.customer_region": {
                    "Target": {
                      "Entity": "customer.customer_region"
                    }
                  }
                },
                "State": "Generated"
              },
              "customer_in_customer_country": {
                "Binding": {
                  "ConceptualEntity": "customer"
                },
                "Phrasings": [
                  {
                    "ID": "customers_are_in_customer_countries",
                    "Preposition": {
                      "Object": {
                        "Role": "customer.customer_country"
                      },
                      "Prepositions": [
                        {
                          "in": {
                            "State": "Generated"
                          }
                        }
                      ],
                      "Subject": {
                        "Role": "customer"
                      }
                    },
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "customer": {
                    "Target": {
                      "Entity": "customer"
                    }
                  },
                  "customer.customer_country": {
                    "Target": {
                      "Entity": "customer.customer_country"
                    }
                  }
                },
                "SemanticSlots": {
                  "Where": {
                    "Role": "customer.customer_country"
                  }
                },
                "State": "Generated"
              },
              "customer_in_customer_region": {
                "Binding": {
                  "ConceptualEntity": "customer"
                },
                "Phrasings": [
                  {
                    "ID": "customers_are_in_customer_regions",
                    "Preposition": {
                      "Object": {
                        "Role": "customer.customer_region"
                      },
                      "Prepositions": [
                        {
                          "in": {
                            "State": "Generated"
                          }
                        }
                      ],
                      "Subject": {
                        "Role": "customer"
                      }
                    },
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "customer": {
                    "Target": {
                      "Entity": "customer"
                    }
                  },
                  "customer.customer_region": {
                    "Target": {
                      "Entity": "customer.customer_region"
                    }
                  }
                },
                "SemanticSlots": {
                  "Where": {
                    "Role": "customer.customer_region"
                  }
                },
                "State": "Generated"
              },
              "snowball_output_has_bop_arr": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.bop_arr"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_bop_arrs",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  },
                  "snowball_output.bop_arr": {
                    "Target": {
                      "Entity": "snowball_output.bop_arr"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_has_cross_sell": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.cross_sell"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_cross_sell",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  },
                  "snowball_output.cross_sell": {
                    "Target": {
                      "Entity": "snowball_output.cross_sell"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_has_customer": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "customer"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_customers",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output"
                      },
                      "Subject": {
                        "Role": "customer"
                      }
                    },
                    "ID": "customers_have_snowball_outputs",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "customer": {
                    "Target": {
                      "Entity": "customer"
                    }
                  },
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_has_customer_churn": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.customer_churn"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_customer_churns",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  },
                  "snowball_output.customer_churn": {
                    "Target": {
                      "Entity": "snowball_output.customer_churn"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_has_downsell": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.downsell"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_downsells",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  },
                  "snowball_output.downsell": {
                    "Target": {
                      "Entity": "snowball_output.downsell"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_has_eop_arr": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.eop_arr"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_eop_arrs",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  },
                  "snowball_output.eop_arr": {
                    "Target": {
                      "Entity": "snowball_output.eop_arr"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_has_grr": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.grr"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_grrs",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  },
                  "snowball_output.grr": {
                    "Target": {
                      "Entity": "snowball_output.grr"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_has_month": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.month"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_months",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  },
                  "snowball_output.month": {
                    "Target": {
                      "Entity": "snowball_output.month"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_has_month_roll": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.month_roll"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_month_rolls",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  },
                  "snowball_output.month_roll": {
                    "Target": {
                      "Entity": "snowball_output.month_roll"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_has_monthyear": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.monthyear"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_monthyears",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  },
                  "snowball_output.monthyear": {
                    "Target": {
                      "Entity": "snowball_output.monthyear"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_has_new_customer": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.new_customer"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_new_customers",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  },
                  "snowball_output.new_customer": {
                    "Target": {
                      "Entity": "snowball_output.new_customer"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_has_nrr": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.nrr"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_nrrs",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  },
                  "snowball_output.nrr": {
                    "Target": {
                      "Entity": "snowball_output.nrr"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_has_period_type": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.period_type"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_period_types",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  },
                  "snowball_output.period_type": {
                    "Target": {
                      "Entity": "snowball_output.period_type"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_has_product_churn": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.product_churn"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_product_churns",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  },
                  "snowball_output.product_churn": {
                    "Target": {
                      "Entity": "snowball_output.product_churn"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_has_product_key": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.product_key"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_product_keys",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  },
                  "snowball_output.product_key": {
                    "Target": {
                      "Entity": "snowball_output.product_key"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_has_snowball_key": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.snowball_key"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_snowball_keys",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  },
                  "snowball_output.snowball_key": {
                    "Target": {
                      "Entity": "snowball_output.snowball_key"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_has_upsell": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.upsell"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_upsell",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  },
                  "snowball_output.upsell": {
                    "Target": {
                      "Entity": "snowball_output.upsell"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_has_year": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.year"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_years",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  },
                  "snowball_output.year": {
                    "Target": {
                      "Entity": "snowball_output.year"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_month_roll_has_variation_date_hierarchy": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.month_roll.variation.date_hierarchy"
                      },
                      "Subject": {
                        "Role": "snowball_output.month_roll"
                      }
                    },
                    "ID": "month_rolls_have_month_roll_date_hierarchies",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output.month_roll": {
                    "Target": {
                      "Entity": "snowball_output.month_roll"
                    }
                  },
                  "snowball_output.month_roll.variation.date_hierarchy": {
                    "Target": {
                      "Entity": "snowball_output.month_roll.variation.date_hierarchy"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_month_roll_variation_date_hierarchy_has_day": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.month_roll.variation.date_hierarchy.day"
                      },
                      "Subject": {
                        "Role": "snowball_output.month_roll.variation.date_hierarchy"
                      }
                    },
                    "ID": "month_roll_date_hierarchies_have_month_roll_days",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output.month_roll.variation.date_hierarchy": {
                    "Target": {
                      "Entity": "snowball_output.month_roll.variation.date_hierarchy"
                    }
                  },
                  "snowball_output.month_roll.variation.date_hierarchy.day": {
                    "Target": {
                      "Entity": "snowball_output.month_roll.variation.date_hierarchy.day"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_month_roll_variation_date_hierarchy_has_month": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.month_roll.variation.date_hierarchy.month"
                      },
                      "Subject": {
                        "Role": "snowball_output.month_roll.variation.date_hierarchy"
                      }
                    },
                    "ID": "month_roll_date_hierarchies_have_month_roll_months",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output.month_roll.variation.date_hierarchy": {
                    "Target": {
                      "Entity": "snowball_output.month_roll.variation.date_hierarchy"
                    }
                  },
                  "snowball_output.month_roll.variation.date_hierarchy.month": {
                    "Target": {
                      "Entity": "snowball_output.month_roll.variation.date_hierarchy.month"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_month_roll_variation_date_hierarchy_has_quarter": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.month_roll.variation.date_hierarchy.quarter"
                      },
                      "Subject": {
                        "Role": "snowball_output.month_roll.variation.date_hierarchy"
                      }
                    },
                    "ID": "month_roll_date_hierarchies_have_month_roll_quarters",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output.month_roll.variation.date_hierarchy": {
                    "Target": {
                      "Entity": "snowball_output.month_roll.variation.date_hierarchy"
                    }
                  },
                  "snowball_output.month_roll.variation.date_hierarchy.quarter": {
                    "Target": {
                      "Entity": "snowball_output.month_roll.variation.date_hierarchy.quarter"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_month_roll_variation_date_hierarchy_has_year": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.month_roll.variation.date_hierarchy.year"
                      },
                      "Subject": {
                        "Role": "snowball_output.month_roll.variation.date_hierarchy"
                      }
                    },
                    "ID": "month_roll_date_hierarchies_have_month_roll_years",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output.month_roll.variation.date_hierarchy": {
                    "Target": {
                      "Entity": "snowball_output.month_roll.variation.date_hierarchy"
                    }
                  },
                  "snowball_output.month_roll.variation.date_hierarchy.year": {
                    "Target": {
                      "Entity": "snowball_output.month_roll.variation.date_hierarchy.year"
                    }
                  }
                },
                "State": "Generated"
              }
            },
            "Version": "3.5.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "9b13fe09-25c7-4752-9063-7c73270c95d1",
        "fromColumn": "month_roll",
        "fromTable": "snowball_output",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_7abf7843-4cd2-4da4-b8ff-6743e3570bd3"
      },
      {
        "name": "AutoDetected_570b79c8-2bbc-4020-9098-09440a10498a",
        "fromColumn": "customer_key",
        "fromTable": "snowball_output",
        "toColumn": "customer_key",
        "toTable": "customer"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "customer",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "customer_key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9ca863cf-e623-4920-aa29-f72f9e710d2b",
            "sourceColumn": "customer_key",
            "summarizeBy": "none"
          },
          {
            "name": "customer_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7e03d5a0-0d7c-4e53-b166-cbcf4a237fb8",
            "sourceColumn": "customer_id",
            "summarizeBy": "none"
          },
          {
            "name": "customer_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "94ba15ab-852d-49e4-b310-119f06d89c99",
            "sourceColumn": "customer_name",
            "summarizeBy": "none"
          },
          {
            "name": "customer_country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2579d630-fae2-47d4-8946-c21a522e9760",
            "sourceColumn": "customer_country",
            "summarizeBy": "none"
          },
          {
            "name": "customer_region ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cc254d95-747f-4081-8060-a4a2c2e27f32",
            "sourceColumn": "customer_region ",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "6cb5bb90-2095-4141-a75f-385046eca225",
        "partitions": [
          {
            "name": "customer",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\SanthoshS\\Downloads\\customer.csv\"),[Delimiter=\",\", Columns=6, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"customer_key\", type text}, {\"customer_id\", Int64.Type}, {\"customer_name\", type text}, {\"customer_country\", type text}, {\"customer_region \", type text}, {\"dimension_1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"dimension_1\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_9a538db5-a7d3-4792-9515-6a1ff1ba2831",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "371555e8-02b0-4667-9943-a9b982542637",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "dcdb5e20-bb3a-42f8-8282-d95997da29ac",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "756ba3ab-2f0e-4f44-8c44-211b01883cd3",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "a942615b-9651-4fb0-97dc-0d0ea65c0a32",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "30cfd683-166e-4ba2-9d6d-3deda7270eac",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "7db4a843-a726-4b0c-aaa2-854c7ecfc654",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "540969b8-b2e0-431f-a9ae-e202ac71336f",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "b1de2924-e58f-4eb4-9ae8-9681a549ffb1",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "2bead990-eb4d-44b9-8e10-72e4597eb425",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "b9d9bdc4-e5bc-499a-9bbe-7c40985a1dbd",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "b6cc96e2-437c-4209-8e1e-e0392d7de7fd",
                "ordinal": 3
              }
            ],
            "lineageTag": "23023003-fafb-430c-9253-5be0b407f9ef"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "4d9e23c3-2cf9-49bf-a438-08f625a1d2d3",
        "partitions": [
          {
            "name": "DateTableTemplate_9a538db5-a7d3-4792-9515-6a1ff1ba2831",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "snowball_output",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "snowball_key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "711b32b5-328d-4447-b687-f71769843b41",
            "sourceColumn": "snowball_key",
            "summarizeBy": "none"
          },
          {
            "name": "customer_key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "75a080a0-3743-4bbb-a5ca-1d8580b45f9e",
            "sourceColumn": "customer_key",
            "summarizeBy": "none"
          },
          {
            "name": "product_key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f725ad95-1bd1-448b-afab-f91a9e307b0a",
            "sourceColumn": "product_key",
            "summarizeBy": "none"
          },
          {
            "name": "month_roll",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "647e36d0-d214-45e3-a27d-a51745603a3f",
            "sourceColumn": "month_roll",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_7abf7843-4cd2-4da4-b8ff-6743e3570bd3"
                },
                "isDefault": true,
                "relationship": "9b13fe09-25c7-4752-9063-7c73270c95d1"
              }
            ]
          },
          {
            "name": "period_type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c01e11d2-b42e-4bd5-b1f2-efa225bc1842",
            "sourceColumn": "period_type",
            "summarizeBy": "none"
          },
          {
            "name": "bop_arr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "fda339ea-9188-461e-9e71-cd151c175867",
            "sourceColumn": "bop_arr",
            "summarizeBy": "sum"
          },
          {
            "name": "customer_churn",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "a0e26c3c-d1d6-497d-9dc9-882852972190",
            "sourceColumn": "customer_churn",
            "summarizeBy": "sum"
          },
          {
            "name": "product_churn",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d6850937-b586-4168-8049-b52eac054922",
            "sourceColumn": "product_churn",
            "summarizeBy": "sum"
          },
          {
            "name": "downsell",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b6d9ba32-79af-425b-8722-52c59c5f4fc6",
            "sourceColumn": "downsell",
            "summarizeBy": "sum"
          },
          {
            "name": "grr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "3772ca54-01d7-4b7f-84b2-5e668e942563",
            "sourceColumn": "grr",
            "summarizeBy": "sum"
          },
          {
            "name": "upsell",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "8291a21c-3512-40c0-838a-2c4757368100",
            "sourceColumn": "upsell",
            "summarizeBy": "sum"
          },
          {
            "name": "cross_sell",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "21562e83-e5d3-46a6-8f41-b1c08c21836c",
            "sourceColumn": "cross_sell",
            "summarizeBy": "sum"
          },
          {
            "name": "nrr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "1882ef70-84d3-4c16-878d-98584f3a1a94",
            "sourceColumn": "nrr",
            "summarizeBy": "sum"
          },
          {
            "name": "new_customer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "4c4501ff-d8cf-4e0f-8658-b9687e154d28",
            "sourceColumn": "new_customer",
            "summarizeBy": "sum"
          },
          {
            "name": "eop_arr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "3f9a646f-926f-4549-a7a8-fe279979169f",
            "sourceColumn": "eop_arr",
            "summarizeBy": "sum"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f2f66444-a224-4cb9-8232-45841047b87d",
            "sourceColumn": "Year",
            "summarizeBy": "sum"
          },
          {
            "name": "month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ee3c7709-74ca-4b62-91c4-a9f4748a8795",
            "sourceColumn": "month",
            "summarizeBy": "none"
          },
          {
            "name": "monthyear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f2cc82b5-8eae-409e-8e91-02695c8639df",
            "sourceColumn": "monthyear",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "ad589b9c-5e67-4df5-85c9-ad279fec4d71",
        "partitions": [
          {
            "name": "snowball_output",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\SanthoshS\\Downloads\\snowball_output.csv\"),[Delimiter=\",\", Columns=15, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"snowball_key\", type text}, {\"customer_key\", type text}, {\"product_key\", type text}, {\"month_roll\", type date}, {\"period_type\", type text}, {\"bop_arr\", type number}, {\"customer_churn\", type number}, {\"product_churn\", type number}, {\"downsell\", type number}, {\"grr\", type number}, {\"upsell\", type number}, {\"cross_sell\", Int64.Type}, {\"nrr\", type number}, {\"new_customer\", type number}, {\"eop_arr\", type number}}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Changed Type\", each ([month_roll] <> #date(2018, 7, 1) and [month_roll] <> #date(2018, 8, 1) and [month_roll] <> #date(2018, 9, 1) and [month_roll] <> #date(2018, 10, 1) and [month_roll] <> #date(2018, 11, 1) and [month_roll] <> #date(2018, 12, 1) and [month_roll] <> #date(2019, 7, 1) and [month_roll] <> #date(2019, 8, 1) and [month_roll] <> #date(2019, 9, 1) and [month_roll] <> #date(2019, 10, 1) and [month_roll] <> #date(2019, 11, 1) and [month_roll] <> #date(2019, 12, 1) and [month_roll] <> #date(2020, 7, 1) and [month_roll] <> #date(2020, 8, 1) and [month_roll] <> #date(2020, 9, 1) and [month_roll] <> #date(2020, 10, 1) and [month_roll] <> #date(2020, 11, 1) and [month_roll] <> #date(2020, 12, 1))),",
                "    #\"Duplicated Column\" = Table.DuplicateColumn(#\"Filtered Rows\", \"month_roll\", \"month_roll - Copy\"),",
                "    #\"Extracted Year\" = Table.TransformColumns(#\"Duplicated Column\",{{\"month_roll - Copy\", Date.Year, Int64.Type}}),",
                "    #\"Duplicated Column1\" = Table.DuplicateColumn(#\"Extracted Year\", \"month_roll\", \"month_roll - Copy.1\"),",
                "    #\"Extracted Month Name\" = Table.TransformColumns(#\"Duplicated Column1\", {{\"month_roll - Copy.1\", each Date.MonthName(_), type text}}),",
                "    #\"Inserted Merged Column\" = Table.AddColumn(#\"Extracted Month Name\", \"Merged\", each Text.Combine({[#\"month_roll - Copy.1\"], Text.From([#\"month_roll - Copy\"], \"en-US\")}, \"\"), type text),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Inserted Merged Column\",{{\"month_roll - Copy\", \"Year\"}, {\"month_roll - Copy.1\", \"month\"}, {\"Merged\", \"monthyear\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_7abf7843-4cd2-4da4-b8ff-6743e3570bd3",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "5a390daa-fbed-412e-b4cb-e6553c298df0",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "9f6c429c-faff-402e-a7bb-a0ef5a33425b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "31110a07-2d59-4e7b-a64e-00b5d308bdca",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "e39f328a-c07c-4464-865e-9b3abd469f24",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "3822a930-4cf3-49e1-a75c-03f523fa8690",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "8cf52f64-c6d9-4033-aa1f-e4895fcff4b3",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "f2deaaa7-8b27-469b-921d-40cd0ce3771c",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "102e5f69-d2e4-43eb-9b04-b6190706c6d1",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "933eed27-e98d-4bbe-a200-7cad3643230f",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "454e88c9-3175-4cc5-a3e9-c964e512da4b",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "84fe1631-f6b7-4978-ba79-60150cd4eb46",
                "ordinal": 3
              }
            ],
            "lineageTag": "09e0818f-8ffe-40bb-8906-739fc7765d8b"
          }
        ],
        "isHidden": true,
        "lineageTag": "ab724743-3269-42bc-ba2f-0282f73d8b99",
        "partitions": [
          {
            "name": "LocalDateTable_7abf7843-4cd2-4da4-b8ff-6743e3570bd3",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('snowball_output'[month_roll])), 1, 1), Date(Year(MAX('snowball_output'[month_roll])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      }
    ]
  }
}